### ISSUE TITLE
Persistency

### ISSUE THREAD

**Issue by amityahav** [paypal/junodb#112]
Hey, just wondering how Juno is persistent on disk? Thanks

**Comment by ehmo** [comment]
Haven’t dug through the code too much yet, but it seems to use a fork of [RocksDB](https://github.com/paypal/junodb/blob/main/cmd/storageserv/storage/db/rocksdb.go)

**Comment by justinfx** [comment]
The article says it currently uses RocksDB but has a pluggable storage implementation to swap it to other storage techs

https://medium.com/paypal-tech/unlocking-the-power-of-junodb-paypals-key-value-store-goes-open-source-ee85f935bdc1

**Comment by NeetishPathak** [comment]
Yes,  rocksdb , with db path set in config . https://github.com/paypal/junodb/blob/main/package_config/package/junostorageserv/config/config.toml#L113

**Comment by varuntechie** [comment]
@amityahav hope your question is answered.

**Comment by gmarcial** [comment]
@amityahav, more details in articles about JunoDB:
- [Summary by Quastor.](https://blog.quastor.org/p/paypal-built-database-serves-350-billion-requests-per-day)
- [Official PayPal article.](https://medium.com/paypal-tech/unlocking-the-power-of-junodb-paypals-key-value-store-goes-open-source-ee85f935bdc1)
