### ISSUE TITLE
tecbot/gorocksdb Not Uploaded

### ISSUE THREAD

**Issue by soiya** [paypal/junodb#125]
The import statement in cmd/dbscanserv/app/cmd.go references "juno/third_party/forked/tecbot/gorocksdb"
https://github.com/paypal/junodb/blob/f1899e49c5a66c0c02de2d9b26588ae0c8d691ed/cmd/dbscanserv/app/cmd.go#L32

 but only golang/glog exists under the juno/third_party/forked directory. Is this intentional?
 
<img width="809" alt="image" src="https://github.com/paypal/junodb/assets/4236586/3a5f6d58-096a-4ff5-9982-d0b5e3283f58">

**Comment by NeetishPathak** [comment]
Third party dependencies are pulled during build
https://github.com/paypal/junodb/blob/main/third_party/apply_patch.sh

**Comment by soiya** [comment]
Thank you! Now that I understand this was intentional, I will close this issue.
