### ISSUE TITLE
Question: if rocksdb as storage, ttl data  is removed or just marked as deleted

### ISSUE THREAD

**Issue by ben1009** [paypal/junodb#141]
As the title, if choose rocksdb as storage. If ttl meets, the data will be removed from the db or just  leave a deleted tombstone, will be removed later by full tree compaction, thanks.

**Comment by NeetishPathak** [comment]
All expired keys are removed during compaction.

**Comment by ben1009** [comment]
> All expired keys are removed during compaction.

So when ttl meet, the disk space will not be reclaimed

**Comment by NeetishPathak** [comment]
Correct, it will not be reclaimed by default. 
Current solution depends on auto compaction to clean up and reclaim that space.
